### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by achul123** [Kamesuta/BungeePteroPower#2]
There are several bugs at the start level when we start the server it does not give us the title in any case I do not understand the autostart does what then should do when we try to connect like /server pvp it turns on the server

**Comment by Kamesuta** [comment]
Did you granted autostart permissions?  
You need to add permission to player to use autostart feature.  

In Bungeecord `config.yml` file.
```yml
permissions:
  default:
  // player can start all server
  - ptero.autostart.*
  // player can start specific server
  - ptero.autostart.<server_name>
 ```
